### ISSUE TITLE
Actual site contents do not seem to be reflected in this repo

### ISSUE THREAD

**Issue by PureTryOut** [darlinghq/www.darlinghq.org#20]
In a blog post I found that the site has been completely rewritten at some point, and it seems that the rewrite hasn't made it to this git repo for some reason.
Please update this repo with the latest sources, there is a change I would like to make which just isn't available in this repository right now.

**Comment by LubosD** [comment]
> Please update this repo with the latest sources, there is a change I would like to make which just isn't available in this repository right now.

What change?

**Comment by PureTryOut** [comment]
The installation instructions for Alpine Linux. It says you need to install Python 2 but that has been dropped from it's repositories for quite a while. But rather than you now applying some relevant change for that directly on the website, please update this repo with the current website contents so this and other future changes can be made by other contributors like myself :wink: 

And if you for some reason don't want to do that (I don't see why you wouldn't tbh :thinking:) then at least archive this repository so it's clear it's obsolete.

Also unrelated, is there a non-Discord (preferably Matrix or IRC) chat room available somewhere?

**Comment by LubosD** [comment]
You're jumping to conclusions too fast. The documentation site is in this repository: https://github.com/darlinghq/darling-docs - notice the change in domain when you visit it: https://docs.darlinghq.org/ != https://www.darlinghq.org/

Python 2 is still needed.

No, we only have Discord.

**Comment by PureTryOut** [comment]
I know Python 2 is needed, but since it isn't available in Alpine Linux any more the instructions aren't relevant any more. The change I would introduce is (sadly) just removing the instructions for now till Darling is updated to support macOS 12.3+.

I missed the change in domain, I know the docs are somewhere else but missed the fact that the installation instructions are on there as well. Sorry for that, I'll submit a pull-request to that repo. Still it would be great to have this repo updated with the latest sources, I'm sure there are things that now or in the future could be improved and right now this repository is just misleading honestly.

Too bad that you only have Discord, I'm sure you're missing out on a lot of people that would be useful to have in the chat due to it being a proprietary and centralized service. Consider setting up a bridge to e.g. Matrix. But if that's how it is, then that's just how it is :shrug:

**Comment by CuriousTommy** [comment]
> The change I would introduce is (sadly) just removing the instructions for now till Darling is updated to support macOS 12.3+.

Even then, we would still want to build the python2 code for backwards compatibility. I recommend reading https://github.com/darlinghq/darling/issues/1074#issuecomment-993577983 to get a better understanding on the whole python2 situation.

> I'm sure there are things that now or in the future could be improved and right now this repository is just misleading honestly.

I disagree, the repo's name (`www.darlinghq.org`) make it pretty clear that this is for the main website and nothing else.
* [`darlinghq / www.darlinghq.org`](https://github.com/darlinghq/www.darlinghq.org) - Main website
* [`darlinghq / darling-docs`](https://github.com/darlinghq/darling-docs) - Docs website
* [`darlinghq / darling`](https://github.com/darlinghq/darling) - Source code to Darling
