### ISSUE TITLE
anbox is not wine-like

### ISSUE THREAD

**Issue by Mis012** [darlinghq/www.darlinghq.org#22]
I don't want this to feel like shameless self-promotion since I created https://gitlab.com/android_translation_layer/android_translation_layer/ which actually is wine-like in that it reimplements android APIs, but the statement that anbox is similar to wine/darling is simply incorrect. What anbox does is run a full AOSP installation in a container, which is closer to a VM than to a translation layer. Obviously a mention of android_translation_layer would be nice, but more realistically anbox shouldn't be mentioned because it's just confusing (even android_translation_layer is less wine-like than darling, due to the way android works)

**Comment by trungnt2910** [comment]
Using your own arguments, Darling is also not WINE-like because it runs a Darwin/macOS-compatible installation in a Linux container, as Darling also uses PID namespaces.
